# wordlist.py
word_list = [
    'abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward', 'axiom', 'azure', 'bagpipes',
    'bandwagon', 'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz', 'blizzard', 'boggle', 'bookworm',
    'boxcar', 'boxful', 'buckaroo', 'buffalo', 'buffoon', 'buxom', 'buzzard', 'buzzing', 'buzzwords',
    'caliph', 'cobweb', 'cockiness', 'croquet', 'crypt', 'curacao', 'cycle', 'daiquiri', 'dirndl',
    'disavow', 'dizzying', 'duplex', 'dwarves', 'embezzle', 'equip', 'espionage', 'euouae', 'exodus',
    'faking', 'fishhook', 'fixable', 'fjord', 'flapjack', 'flopping', 'fluffiness', 'flyby', 'foxglove',
    'frazzled', 'frizzled', 'fuchsia', 'funny', 'gabby', 'galaxy', 'galvanize', 'gazebo', 'giaour',
    'gizmo', 'glowworm', 'glyph', 'gnarly', 'gnostic', 'gossip', 'grogginess', 'haiku', 'haphazard',
    'hyphen', 'iatrogenic', 'icebox', 'injury', 'ivory', 'ivy', 'jackpot', 'jaundice', 'jawbreaker',
    'jaywalk', 'jazziest', 'jazzy', 'jelly', 'jigsaw', 'jinx', 'jiujitsu', 'jockey', 'jogging', 'joking',
    'jovial', 'joyful', 'juicy', 'jukebox', 'jumbo', 'kayak', 'kazoo', 'keyhole', 'khaki', 'kilobyte',
    'kiosk', 'kitsch', 'kiwifruit', 'klutz', 'knapsack', 'larynx', 'lengths', 'lucky', 'luxury', 'lymph',
    'marquis', 'matrix', 'megahertz', 'microwave', 'mnemonic', 'mystify', 'naphtha', 'nightclub',
    'nowadays', 'numbskull', 'nymph', 'onyx', 'ovary', 'oxidize', 'oxygen', 'pajama', 'peekaboo',
    'phlegm', 'pixel', 'pizazz', 'pneumonia', 'polka', 'pshaw', 'psyche', 'puppy', 'puzzling', 'quartz',
    'queue', 'quips', 'quixotic', 'quiz', 'quizzes', 'quorum', 'razzmatazz', 'rhubarb', 'rhythm',
    'rickshaw', 'schnapps', 'scratch', 'shiv', 'snazzy', 'sphinx', 'spritz', 'squawk', 'staff',
    'strength', 'strengths', 'stretch', 'stronghold', 'stymied', 'subway', 'swivel', 'syndrome',
    'thriftless', 'thumbscrew', 'topaz', 'transcript', 'transgress', 'transplant', 'triphthong',
    'twelfth', 'twelfths', 'unknown', 'unworthy', 'unzip', 'uptown', 'vaporize', 'vixen', 'vodka',
    'voodoo', 'vortex', 'voyeurism', 'walkway', 'waltz', 'wave', 'wavy', 'waxy', 'wellspring', 'wheezy',
    'whiskey', 'whizzing', 'whomever', 'wimpy', 'witchcraft', 'wizard', 'woozy', 'wristwatch', 'wyvern',
    'xylophone', 'yachtsman', 'yippee', 'yoked', 'youthful', 'yummy', 'zephyr', 'zigzag', 'zigzagging',
    'zilch', 'zipper', 'zodiac', 'zombie', 
    # Add more words to make it 500 words long
    'abacaxi', 'abandoned', 'abdicate', 'aberrant', 'abjectly', 'ablation', 'abnormal', 'abrasion', 'absentee',
    'absinthe', 'absolved', 'absorbed', 'abstains', 'abstract', 'abundant', 'academia', 'academics', 'accidents',
    'accolade', 'accurate', 'accusing', 'acquaint', 'acquired', 'acquits', 'acreage', 'acronym', 'activate',
    'actually', 'actuator', 'addicted', 'addition', 'adhesive', 'adjutant', 'admirals', 'admiring', 'admitted',
    'adopting', 'adoption', 'adultery', 'advanced', 'advising', 'advocate', 'aerobics', 'aesthetic', 'affecting',
    'affected', 'affinity', 'affirmed', 'afflicts', 'agitated', 'alarming', 'algebraic', 'allegedly', 'allergens',
    'alligator', 'allocated', 'allotment', 'allowance', 'alluding', 'almanacs', 'alterable', 'alteration', 'altercation',
    'alternates', 'altitudes', 'aluminum', 'amalgamate', 'amaryllis', 'amazingly', 'ambitious', 'ambushed', 'amendment',
    'amenities', 'ammunition', 'amorphous', 'amounting', 'amputated', 'amusement', 'amusingly', 'anagrams', 'analysis',
    'analytical', 'analyzing', 'anarchist', 'anecdotal', 'anecdotes', 'anesthesia', 'angriest', 'anguished', 'animated',
    'animations', 'animosity', 'annealing', 'announcer', 'annoyance', 'annulling', 'anomalies', 'anonymity', 'answering',
    'antagonize', 'antecedent', 'anterior', 'anthology', 'antibodies', 'anticline', 'antiquated', 'antiquities', 'antitrust',
    'anxieties', 'apartment', 'apathetic', 'apathetically', 'apologies', 'apologized', 'apothecary', 'appealing', 'appeared',
    'appendage', 'appendices', 'applauding', 'applause', 'applicant', 'applicable', 'appointees', 'appraisal', 'apprehend',
    'apprentice', 'approaches', 'approved', 'approximately', 'aquariums', 'arbitrary', 'arboretum', 'architect', 'arguably',
    'aristocrat', 'aromatic', 'arousing', 'arranging', 'arresting', 'arrogance', 'arrogant', 'arrows', 'arthritis', 'artichoke',
    'artifacts', 'artificial', 'artillery', 'ascendancy', 'ascending', 'ascension', 'ascertain', 'ascribing', 'aspiration',
    'aspirin', 'assailant', 'assassins', 'assaulted', 'assembled', 'assembler', 'assembly', 'asserting', 'assertion', 'assertive',
    'assessing', 'assessment', 'assigning', 'assignment', 'assimilate', 'assistant', 'assisting', 'associate', 'assortment',
    'assuming', 'assurance', 'asteroid', 'astonished', 'astonishing', 'astounded', 'astounding', 'astronaut', 'astronomy',
    'atrocities', 'atrocious', 'atrophy', 'attached', 'attachment', 'attacking', 'attempted', 'attempting', 'attendance',
    'attending', 'attention', 'attentive', 'attested', 'attesting', 'attorney', 'attracting', 'attraction', 'attractive',
    'attributes', 'attributing', 'audacious', 'audacity', 'audible', 'audience', 'auditing', 'auditions', 'augmenting',
    'auspicious', 'authentic', 'authoring', 'authority', 'autograph', 'automaker', 'automatic', 'automobile', 'autonomous',
    'available', 'avalanche', 'averaging', 'avoidance', 'awakened', 'awakening', 'awareness', 'awkwardly', 'backbones', 'backdoor',
    'background', 'backpack', 'backstage', 'backtrack', 'backwards', 'bacteria', 'badgering', 'balancing', 'ballistic', 'ballooned',
    'bamboozle', 'bandaging', 'bandwidth', 'banished', 'banishing', 'bankroll', 'bankrupt', 'baptized', 'barbaric', 'barbecue',
    'barbecue', 'barbershop', 'barricade', 'barrister', 'baseballs', 'basements', 'battering', 'battling', 'beachfront', 'beanstalk',
    'beautician', 'beautiful', 'beautified', 'beautifies', 'beckoning', 'bedspread', 'befuddled', 'beginners', 'beginning', 'behavioral',
    'behaviors', 'belaboring', 'believable', 'believers', 'believing', 'bellyache', 'belonging', 'belongings', 'beneficial', 'benefiting',
    'benefitted', 'benevolent', 'bequeathed', 'besieging', 'besmirched', 'bestseller', 'betraying', 'bettering', 'bewildered', 'bewitching',
    'bibliography', 'bickering', 'bicycling', 'biography', 'biological', 'biologist', 'biometrics', 'biopsies', 'biosphere', 'biracial',
    'birthdays', 'birthmark', 'birthrate', 'biscuit', 'blackboard', 'blackened', 'blackened', 'blackjack', 'blackmail', 'blacksmith',
    'blameless', 'blasphemy', 'bleachers', 'blender', 'blindfold', 'blindingly', 'blistering', 'blockade', 'blockage', 'blockbuster',
    'blockhead', 'bloodhound', 'bloodshed', 'blossomed', 'blubbering', 'blueberry', 'blueprints', 'blunder', 'blunders', 'blundering',
    'blurriness', 'boarding', 'boardroom', 'boasting', 'boatload', 'bobblehead', 'bobsledding', 'bodybuilder', 'bodyguard', 'bodyguards',
    'boisterous', 'bombarded', 'bombarding', 'bonanza', 'bondage', 'bookcases', 'bookkeeper', 'bookmark', 'bookshelf', 'boondoggle',
    'boondocks', 'booster', 'borderline', 'borrowing', 'bottomless', 'bottleneck', 'bouldering', 'boundaries', 'bounding', 'bountiful',
    'bouquet', 'bowling', 'boycotting', 'bracelet', 'brackish', 'braggart', 'brainless', 'brainstorm', 'brainwash', 'brainwashed',
    'brainwashing', 'bravado', 'brazenness', 'breakaway', 'breakdown', 'breakfast', 'breakneck', 'breakouts', 'breakthrough', 'breathing',
    'breathless', 'breathtaking', 'breeder', 'brethren', 'brevet', 'breviary', 'bricklaying', 'briefcase', 'briefings', 'brigadier',
    'brightened', 'brightness', 'brilliant', 'brimstone', 'brindled', 'broadband', 'broadcast', 'broadening', 'broadside', 'brochures',
    'brokerage', 'bromance', 'bromide', 'bronchial', 'bronze', 'brotherhood', 'brought', 'brownie', 'browsing', 'brunette', 'brushing',
    'brutality', 'brutalize', 'bubble', 'bubbles', 'bubbly', 'buckwheat', 'bucolic', 'buffalo', 'buffering', 'buffing', 'buffoonery',
    'bugle', 'bulldozer', 'bulletin', 'bumpkin', 'bungalow', 'bunny', 'burglary', 'burglars', 'burgundy', 'burlesque', 'burrowed', 'burrowing',
    'busboy', 'bushwhack', 'businessman', 'businesswoman', 'butchery', 'buttercup', 'butterfly', 'butterscotch', 'buttoning', 'buxom',
    'buzzards', 'buzzers', 'buzzing', 'buzzwords', 'bygone', 'bylaw', 'bypass', 'byproduct', 'byway', 'cabana', 'cabbage', 'cabbages',
    'cabinet', 'cabinets', 'cable', 'caboose', 'cabotage', 'caffeine', 'cafeteria', 'cagey', 'cajoling', 'calamity', 'calculated', 'calculator',
    'calculus', 'caliphate', 'calligraphy', 'calling', 'callous', 'callously', 'callousness', 'calmly', 'caloric', 'caloric', 'camcorder',
    'camellias', 'camera', 'cameras', 'camouflage', 'campers', 'campaign', 'campground', 'campus', 'canary', 'cancellation', 'cancerous',
    'candidate', 'candlelight', 'candlestick', 'candy', 'canister', 'cannery', 'cannibal', 'cannibalism', 'cannibalistic', 'cannister', 'canon',
    'canopy', 'canteen', 'canyon', 'capably', 'capacious', 'capacitor', 'capacity', 'capillary', 'capitulate', 'capricious', 'capsize', 'capsized',
    'captaincy', 'captions', 'captivity', 'captivating', 'captivation', 'captivator', 'captives', 'captors', 'caramel', 'caravan', 'carbonation',
    'cardiac', 'cardigan', 'cardinal', 'cardiologist', 'cardiology', 'careening', 'carefully', 'caregivers', 'careless', 'carelessly', 'caressing',
    'caretaker', 'caribou', 'caring', 'carnation', 'carpenter', 'carpeting', 'carpetmaker', 'carpool', 'carriage', 'carriages', 'carried', 'carrot',
    'carry', 'carryover', 'cartel', 'cartilage', 'cartography', 'carton', 'cartoons', 'cartridge', 'carvings', 'cascade', 'cascades', 'casebook',
    'casework', 'cashier', 'casings', 'cassava', 'cassette', 'castaway', 'castaways', 'casting', 'castle', 'casual', 'casually', 'casualness', 'casualties',
    'casualty', 'catalyst', 'catapult', 'catastrophe', 'catcher', 'catching', 'categorically', 'categories', 'catered', 'catering', 'catfish', 'cathedrals',
    'cathodes', 'catnapped', 'cattail', 'cattleman', 'cattlemen', 'caught', 'caulking', 'causality', 'causation', 'caused', 'causes', 'causing', 'cauterized',
    'cautious', 'cautiously', 'cautiousness', 'cavern', 'caverns', 'caviar', 'cavity', 'ceasefire', 'ceasing', 'cedarwood', 'celebrated', 'celebration',
    'celebrities', 'celebrity', 'celestial', 'celibacy', 'celibate', 'cellar', 'cellular', 'cemented', 'cemeteries', 'censored', 'censorship', 'censures',
    'centaur', 'centigrade', 'centimeter', 'centipede', 'centrifugal', 'centrifuge', 'centripetal', 'centuries', 'centurion', 'ceramic', 'ceramics',
    'cerebellum', 'cerebral', 'cerebrum', 'ceremonies', 'ceremonious', 'ceremony', 'certified', 'certifies', 'certify', 'certitude', 'cessation',
    'cesspool', 'chafing', 'chagrin', 'chains', 'chainsaw', 'chained', 'chairlift', 'chairman', 'chairwoman', 'chalkboard', 'challenge', 'chameleon',
    'chamois', 'champagne', 'champions', 'chancing', 'changeling', 'changing', 'channels', 'chapel', 'chapels', 'chaplain', 'chapped', 'charcoal',
    'chargrilled', 'chariots', 'charisma', 'charitable', 'charities', 'charity', 'charmingly', 'charred', 'charter', 'chartered', 'charting', 'chasm',
    'chassis', 'chastise', 'chastising', 'chatbots', 'chatter', 'chattering', 'chattier', 'chatting', 'chauffeur', 'cheapens', 'cheapness', 'cheating',
    'cheddar', 'cheekbone', 'cheekily', 'cheerful', 'cheerfulness', 'cheering', 'cheerleaders', 'cheerlessly', 'cheeseburger', 'cheesecake', 'cheesecloth',
    'cheetah', 'chemical', 'chemically', 'chemicals', 'chemistry', 'chemist', 'chequered', 'cherished', 'cherishes', 'cherishing', 'cherries', 'cherry',
    'chessboard', 'chested', 'chevrons', 'chewing', 'chicanery', 'chickadee', 'chicken', 'chickens', 'chickpeas', 'chided', 'chiding', 'chieftain',
    'chiffon', 'childbirth', 'childcare', 'childhood', 'childish', 'childishly', 'children', 'childrens', 'chilling', 'chillingly', 'chimera', 'chimney',
    'chimneys', 'chimpanzee', 'chinchilla', 'chinking', 'chipmunk', 'chipper', 'chipset', 'chiropractic', 'chirping', 'chivalrous', 'chivalry', 'chloride',
    'chlorine', 'chocolate', 'choice', 'choicely', 'choiceness', 'choir', 'choirboys', 'choiring', 'choking', 'cholera', 'cholesterol', 'choosing', 'chopsticks',
    'choral', 'chorale', 'chorally', 'chordal', 'chords', 'chorister', 'chortled', 'chortles', 'chowder', 'chromatic', 'chromium', 'chronic', 'chronically',
    'chronicles', 'chronology', 'chrysalis', 'chubby', 'chuckled', 'chuckles', 'chugging', 'chummily', 'chummiest', 'chumminess', 'chummy', 'churning', 'churning',
    'church', 'churches', 'churchgoers', 'churchgoing', 'churchman', 'churchward', 'churlish', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning',
    'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning', 'churning'
]
